import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headre from "@/component/layout/headre";
import Footer from "@/component/layout/footer";
import OfflineBanner from "./(auth)/demo/page";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#ffffff",
};

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Headre />
        {children}
        <Footer />
      </body>
    </html>
  );
}
